#!/usr/bin/osascript
-- Prints a list of (uncompleted) reminders from the specified list. This might be useful for
-- creating some widget in Ubersicht.
--
-- Michele Giugliano, Jan 5th 2018

on run argv
set MyList to item 1 of argv
		tell application "Reminders"
				set AppleScript's text item delimiters to "\n+ "
				set tmp to reminders in list MyList whose completed is true 
				if length of tmp is greater than 0 
						return "+ " & (name of reminders in list MyList  whose completed is true) as string 
				end if
		end tell
end run
